// <auto-generated />
namespace TAF.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addTable_dictionary : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTable_dictionary));
        
        string IMigrationMetadata.Id
        {
            get { return "201603021341475_addTable_dictionary"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
